name: Run code analysis

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: code-analysis
        run: docker run --rm -t -e REPOSITORY_PATH=${{ github.workspace }} shivamrawat10/code-analysis:latest >> $GITHUB_STEP_SUMMARY
